// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.28.3
// source: seat.proto

package cloudbeespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Section int32

const (
	Section_SECTION_A Section = 0
	Section_SECTION_B Section = 1
)

// Enum value maps for Section.
var (
	Section_name = map[int32]string{
		0: "SECTION_A",
		1: "SECTION_B",
	}
	Section_value = map[string]int32{
		"SECTION_A": 0,
		"SECTION_B": 1,
	}
)

func (x Section) Enum() *Section {
	p := new(Section)
	*p = x
	return p
}

func (x Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Section) Descriptor() protoreflect.EnumDescriptor {
	return file_seat_proto_enumTypes[0].Descriptor()
}

func (Section) Type() protoreflect.EnumType {
	return &file_seat_proto_enumTypes[0]
}

func (x Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Section.Descriptor instead.
func (Section) EnumDescriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{0}
}

type Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatNo  int32   `protobuf:"varint,1,opt,name=seat_no,json=seatNo,proto3" json:"seat_no,omitempty"`
	Section Section `protobuf:"varint,2,opt,name=section,proto3,enum=cloudbees.Section" json:"section,omitempty"`
}

func (x *Seat) Reset() {
	*x = Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSeatNo() int32 {
	if x != nil {
		return x.SeatNo
	}
	return 0
}

func (x *Seat) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SECTION_A
}

type AllocatedSeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat *Seat `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AllocatedSeat) Reset() {
	*x = AllocatedSeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocatedSeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatedSeat) ProtoMessage() {}

func (x *AllocatedSeat) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatedSeat.ProtoReflect.Descriptor instead.
func (*AllocatedSeat) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{1}
}

func (x *AllocatedSeat) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *AllocatedSeat) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListSeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section Section `protobuf:"varint,1,opt,name=section,proto3,enum=cloudbees.Section" json:"section,omitempty"`
}

func (x *ListSeatsRequest) Reset() {
	*x = ListSeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatsRequest) ProtoMessage() {}

func (x *ListSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatsRequest.ProtoReflect.Descriptor instead.
func (*ListSeatsRequest) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{2}
}

func (x *ListSeatsRequest) GetSection() Section {
	if x != nil {
		return x.Section
	}
	return Section_SECTION_A
}

type ListSeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllocatedSeat []*AllocatedSeat `protobuf:"bytes,1,rep,name=allocated_seat,json=allocatedSeat,proto3" json:"allocated_seat,omitempty"`
}

func (x *ListSeatsResponse) Reset() {
	*x = ListSeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatsResponse) ProtoMessage() {}

func (x *ListSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatsResponse.ProtoReflect.Descriptor instead.
func (*ListSeatsResponse) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{3}
}

func (x *ListSeatsResponse) GetAllocatedSeat() []*AllocatedSeat {
	if x != nil {
		return x.AllocatedSeat
	}
	return nil
}

type ModifySeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	NewSeat *Seat `protobuf:"bytes,2,opt,name=new_seat,json=newSeat,proto3" json:"new_seat,omitempty"`
}

func (x *ModifySeatRequest) Reset() {
	*x = ModifySeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySeatRequest) ProtoMessage() {}

func (x *ModifySeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySeatRequest.ProtoReflect.Descriptor instead.
func (*ModifySeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{4}
}

func (x *ModifySeatRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ModifySeatRequest) GetNewSeat() *Seat {
	if x != nil {
		return x.NewSeat
	}
	return nil
}

var File_seat_proto protoreflect.FileDescriptor

var file_seat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x74, 0x4e, 0x6f, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65,
	0x73, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x61, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x53, 0x65,
	0x61, 0x74, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65,
	0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x40, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x54, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x61, 0x74, 0x22, 0x64, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x62, 0x65, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x53, 0x65,
	0x61, 0x74, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x61, 0x74, 0x2a, 0x27, 0x0a, 0x07, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x41, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x42, 0x10, 0x01, 0x32, 0x92, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x43, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x62, 0x65, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65,
	0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12,
	0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x53, 0x65, 0x61, 0x74, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x62, 0x65, 0x65, 0x73, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seat_proto_rawDescOnce sync.Once
	file_seat_proto_rawDescData = file_seat_proto_rawDesc
)

func file_seat_proto_rawDescGZIP() []byte {
	file_seat_proto_rawDescOnce.Do(func() {
		file_seat_proto_rawDescData = protoimpl.X.CompressGZIP(file_seat_proto_rawDescData)
	})
	return file_seat_proto_rawDescData
}

var file_seat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_seat_proto_goTypes = []interface{}{
	(Section)(0),              // 0: cloudbees.Section
	(*Seat)(nil),              // 1: cloudbees.Seat
	(*AllocatedSeat)(nil),     // 2: cloudbees.AllocatedSeat
	(*ListSeatsRequest)(nil),  // 3: cloudbees.ListSeatsRequest
	(*ListSeatsResponse)(nil), // 4: cloudbees.ListSeatsResponse
	(*ModifySeatRequest)(nil), // 5: cloudbees.ModifySeatRequest
	(*User)(nil),              // 6: cloudbees.User
}
var file_seat_proto_depIdxs = []int32{
	0, // 0: cloudbees.Seat.section:type_name -> cloudbees.Section
	1, // 1: cloudbees.AllocatedSeat.seat:type_name -> cloudbees.Seat
	6, // 2: cloudbees.AllocatedSeat.user:type_name -> cloudbees.User
	0, // 3: cloudbees.ListSeatsRequest.section:type_name -> cloudbees.Section
	2, // 4: cloudbees.ListSeatsResponse.allocated_seat:type_name -> cloudbees.AllocatedSeat
	6, // 5: cloudbees.ModifySeatRequest.user:type_name -> cloudbees.User
	1, // 6: cloudbees.ModifySeatRequest.new_seat:type_name -> cloudbees.Seat
	3, // 7: cloudbees.Seating.List:input_type -> cloudbees.ListSeatsRequest
	5, // 8: cloudbees.Seating.Modify:input_type -> cloudbees.ModifySeatRequest
	4, // 9: cloudbees.Seating.List:output_type -> cloudbees.ListSeatsResponse
	2, // 10: cloudbees.Seating.Modify:output_type -> cloudbees.AllocatedSeat
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_seat_proto_init() }
func file_seat_proto_init() {
	if File_seat_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_seat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocatedSeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seat_proto_goTypes,
		DependencyIndexes: file_seat_proto_depIdxs,
		EnumInfos:         file_seat_proto_enumTypes,
		MessageInfos:      file_seat_proto_msgTypes,
	}.Build()
	File_seat_proto = out.File
	file_seat_proto_rawDesc = nil
	file_seat_proto_goTypes = nil
	file_seat_proto_depIdxs = nil
}
